node:
  name: worker#1
  ip: 0.0.0.0
  # 0 means random port
  port: 0
  key_path: /Users/derekanderson/Projects/bless/net2/configs/testkeys/ident2/priv.bin
  boot_nodes:
    - /ip4/0.0.0.0/tcp/9527/p2p/12D3KooWH9GerdSEroL2nqjpd2GuE5dwmqNi7uHX7FoywBdKcP4q
  workspace_root: /tmp/worker
  runtime_path: /tmp/runtime
rest:
  ip: 0.0.0.0
  port: 8081
protocol:
  role: worker
logging:
  file_path: stdout
  level: info
repository:
  url: http://localhost:8080/
chain:
  address_key: "alice"
  rpc: "http://0.0.0.0:26657"
